project:
  type: website
  output-dir: docs

website:
  title: "Stella Symonds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - things.qmd 
      - experience.qmd

format:
  html:
    theme: 
    - minty
    - styles.scss
    mainfont: Roboto Serif
    toc: true
    page-layout: full



